### ISSUE TITLE
Trouble executing STARTUP_SQL

### ISSUE THREAD

**Issue by aarongundel** [tutumcloud/tutum-docker-mysql#46]
I'm having some issues with my mysql instance not executing the script in the STARTUP_SQL environment variable.  Here's what I'm doing.  

docker run -d --volumes-from db_vol -v /Users/me/Desktop:/tmp/sql -p 3306:3306 -e MYSQL_PASS="randompass" -e STARTUP_SQL="/tmp/sql/init_database.sql" --name mysql_box tutum/mysql

Where db_vol is a volume created per the default example in the README.  You can see I've set up a volume mapping between my desktop and the /tmp/sql directory.  I have verified that (with nsenter) that init_database.sql is indeed in /tmp/sql/init_database.sql .  From my shell into the mysql_box, I can execute the init_database.sql script by hand -- but the STARTUP_SQL variable seems to be ignored.  Is this change live on dockerhub?  

Thank you!

**Comment by celso** [comment]
Doesn't work for me either. I'm guessing it's because of this:

```
if [[ ! -d $VOLUME_HOME/mysql ]]; then
    echo "=> An empty or uninitialized MySQL volume is detected in $VOLUME_HOME"
    echo "=> Installing MySQL ..."
    if [ ! -f /usr/share/mysql/my-default.cnf ] ; then
        cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
    fi 
    mysql_install_db > /dev/null 2>&1
    echo "=> Done!"  
    echo "=> Creating admin user ..."
    CreateMySQLUser

    if [ -n "${STARTUP_SQL}" ]; then
        echo "=> Initializing DB with ${STARTUP_SQL}"
        ImportSql
    fi
else
    echo "=> Using an existing volume of MySQL"
fi
```

$VOLUME_HOME/mysql was already created, so it never gets to ImportSql()

https://github.com/tutumcloud/tutum-docker-mysql/blob/master/5.6/run.sh

**Comment by tifayuki** [comment]
Just checked the code, it is a PR from a user who need it for testing in development test.
https://github.com/tutumcloud/tutum-docker-mysql/pull/40

But yes, I think it is possible to put the invoke of `Importsql` outside the volume check statement. I will modify it soon.
