### ISSUE TITLE
Can't connect to local MySQL server

### ISSUE THREAD

**Issue by zhangzhengmeng** [tutumcloud/tutum-docker-mysql#68]
Hi there,
I have successfully run the image and log says that everything is ok, but when I try to connect to MySQL server by using the command "mysql -udmin -p" it shows ERROR 2002 (HY000): Can't connect to local MySQL server through socker '/var/run/mysqld/mysqld.sock' (2).
Is there anyone who knows this problem?
Many thanks for the response!

**Comment by tifayuki** [comment]
you have to specify the ip address of the mysql container, like 127.0.0.1. Otherwise you will connect to the unix socket by default, which is not exist.

**Comment by zhangzhengmeng** [comment]
Hi @tifayuki 
Can you tell me how exactly to specify the ip address of the mysql container? Because usually we use 'docker -d -P' to make the container run in background and no need to modify the ip address.
Thanks

**Comment by zhangzhengmeng** [comment]
Ok,  I solved this problem by using the command ' mysql -uadmin  -h <ip address> -p' and it works well.
